#pragma once

// Runs a kernel on the CPU as the GPU does: dispatch(kernel, gx, gy, gz) runs every workgroup of the
// grid (Kernel::workgroup, generated by tools/wgsl2cpp.py). Workgroups are independent, so native
// builds spread them over the hardware threads, each thread with its own copy of the kernel (its
// workgroup and per-lane memory); WebAssembly runs them in order.

#include <algorithm>
#include <cstdint>
#include <memory>
#include <vector>
#ifndef __EMSCRIPTEN__
#include <thread>
#endif

namespace ofm::detail {

template <class Kernel>
void dispatch(const Kernel& kernel, std::uint32_t gx, std::uint32_t gy = 1, std::uint32_t gz = 1) {
  const std::uint32_t n = gx * gy * gz;
  auto work = [&](std::uint32_t first, std::uint32_t step) {
    auto k = std::make_unique<Kernel>(kernel);
    for (std::uint32_t w = first; w < n; w += step) k->workgroup({w % gx, (w / gx) % gy, w / (gx * gy)});
  };
#ifndef __EMSCRIPTEN__
  const std::uint32_t threads = std::min<std::uint32_t>(n, std::max(1u, std::thread::hardware_concurrency()));
  if (threads > 1) {
    std::vector<std::thread> pool;
    for (std::uint32_t t = 0; t < threads; ++t) pool.emplace_back(work, t, threads);
    for (auto& t : pool) t.join();
    return;
  }
#endif
  if (n > 0) work(0, 1);
}

inline std::uint32_t groups(std::uint32_t n, std::uint32_t size) { return (n + size - 1) / size; }

}  // namespace ofm::detail
